export const GET_STOCK_REQUEST = "GET_STOCK_REQUEST";
export const GET_STOCK_SUCCESS = "GET_STOCK_SUCCESS";
export const GET_STOCK_FAILURE = "GET_STOCK_FAILURE";

export const ADD_STOCK_REQUEST = "ADD_STOCK_REQUEST";
export const ADD_STOCK_SUCCESS = "ADD_STOCK_SUCCESS";
export const ADD_STOCK_FAILURE = "ADD_STOCK_FAILURE";

export const UPDATE_STOCK_REQUEST = "UPDATE_STOCK_REQUEST";
export const UPDATE_STOCK_SUCCESS = "UPDATE_STOCK_SUCCESS";
export const UPDATE_STOCK_FAILURE = "UPDATE_STOCK_FAILURE";

export const DELETE_STOCK_REQUEST = "DELETE_STOCK_REQUEST";
export const DELETE_STOCK_SUCCESS = "DELETE_STOCK_SUCCESS";
export const DELETE_STOCK_FAILURE = "DELETE_STOCK_FAILURE";

export const BUY_STOCK_REQUEST = "BUY_STOCK_REQUEST";
export const BUY_STOCK_SUCCESS = "BUY_STOCK_SUCCESS";
export const BUY_STOCK_FAILURE = "BUY_STOCK_FAILURE";